[project]
name = "claude"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "isort>=6.0.1",
    "langchain>=0.3.26",
    "langchain-openai>=0.3.28",
    "mcp>=1.12.0",
]
